spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/simplelog
    username: root
    password: 4316
    driver-class-name: org.mariadb.jdbc.Driver

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true;
        format_sql: true

